version: "3.9"

services:
  model:
    container_name: openadr_model
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/OpenADR-model
    tty : true
    environment:
      IS_SERVER: "False"
      TZ: Asia/Seoul
      DB_NICKNAME: server_on_docker
    # 아래 줄 추가시 해당 python 파일을 실행
    entrypoint: ["sh", "/home/OpenADR-model/entrypoint.sh"]

# local docker 연결시
networks:
  default:
    external: true  # 기존 network와 연결
    name: openadr-docker_default